name = "idkaboutbytes/promise"
version = "2.1.3"
description = "Promise library for Roblox."
license = "MIT"
authors = ["idkaboutbytes"]
repository = "https://github.com/idkaboutbytes/promise"
includes = [
    "pesde.toml",
    "README.md",
    "CHANGELOG.md",
    "default.project.json",
    "sourcemap.json",
    "src/**/*.luau",
]

[target]
environment = "roblox"
lib = "src/init.luau"
build_files = ["src"]
